<Workspace Version="1.2.1.3083" X="521" Y="219" zoom="1" Name="List From Two Item" Description="Creates a list from two items" ID="1459af63-2c67-454b-b33a-804128fd87a2" Category="Regnstrom.Core.List.Create">
  <NamespaceResolutionMap>
    <ClassMap partialName="Category" resolvedName="Revit.Elements.Category" assemblyName="RevitNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="22ba6aba-d80f-4780-b90a-c6ceeb2f9f0b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="210" y="15" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

#Assign your output to the OUT variable.
OUT = [IN[0], IN[1]]</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="49ba6c5a-e5a2-4080-a2ce-d9b59dfe9b53" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="424" y="14" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="list" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="dffbc337-5675-4669-9b4a-3284fcdf3801" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="31" y="-26" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="item1" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="e065a11d-a5cf-4746-93d6-7590fb2aacb6" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="28" y="78" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="item2" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="22ba6aba-d80f-4780-b90a-c6ceeb2f9f0b" start_index="0" end="49ba6c5a-e5a2-4080-a2ce-d9b59dfe9b53" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="dffbc337-5675-4669-9b4a-3284fcdf3801" start_index="0" end="22ba6aba-d80f-4780-b90a-c6ceeb2f9f0b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="e065a11d-a5cf-4746-93d6-7590fb2aacb6" start_index="0" end="22ba6aba-d80f-4780-b90a-c6ceeb2f9f0b" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>